---
title: "README.md"
output: html_document
---

## Load Packages
run_analysis.R first loads the packages data.table and dplyr.

Next, the data is read.  The testing and training, subject, X and y are read along with activity_label and features.  I use these last 2 to contruct a vector with label actitivies that correspond the the y activity codes in the y dataframe and make the column headings for the data.

Then the dataframes are converted to data tables.  Mostly this makes it easier to work with.

Next, the training and testing DTs are combined.  Subject training with subject test, y training and testing and the training data and test data.  Then the training and testing DTs are deleted to clean up environment.  So we now have the 3 data data tables, subject, y and X with all the data from training and testing combined.  And we still have the two data tables activity_lavel and features.

Next using the y and activity_label DTs, I contruct a vector, activities that has the activities corresponding to the y DT activity codes.

Next, using the features DT I change the column names of the X DT.

Next, I pick out from the features DT, the values with mean or std contain in the string using regular expressions.  This creates a logical vector picks.  From picks I create cols vector which is the column number in the DT X that we are going to keep.  These are the means and standard deviations of the data.  X_selected is the DT with only the columns for means and standard deviations.

Now, to make tidy DT, subject, activity and X_select are column combined.  Then using write.table the text file uploaded to assignment page is created.




